plugins {
    id "net.fabricmc.fabric-loom" version "1.16-SNAPSHOT"
    id "maven-publish"
}

version = project.mod_version
group = project.maven_group

repositories {
    maven {
        name = "Fabric"
        url = "https://maven.fabricmc.net/"
    }
    maven {
        name = "Nucleoid"
        url = "https://maven.nucleoid.xyz/"
    }
    mavenCentral()
}

dependencies {
    // Main
    minecraft("com.mojang:minecraft:${project.minecraft_version}")
    implementation("net.fabricmc:fabric-loader:${project.loader_version}")

    // Fabric API
    implementation("net.fabricmc.fabric-api:fabric-api:${project.fabric_version}")

    // Plasmid
    implementation("xyz.nucleoid:plasmid:${project.plasmid_version}")

    // Permissions
    include(implementation("me.lucko:fabric-permissions-api:${project.permissions_version}"))
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
    it.options.encoding = "UTF-8"
}


java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}


base {
    archivesName = project.archives_base_name
}


jar {
    inputs.property "projectName", project.archives_base_name

    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}"}
    }
    from("LICENSE-PICTIONARYWORDLIST") {
        rename { "${it}_${project.archivesBaseName}"}
    }
}
